- name: Cisco ASA Misc commands
  connection: local
  hosts: cisco-asa
  gather_facts: false
  vars:
    cli:
      username: "{{ username }}"
      password: "{{ password }}"
      host: "{{ ansible_host }}"
      authorize: yes
      auth_pass: "{{ auth_pass }}"

  tasks:
     
    - name: Add my  NTP servers on Cisco ASA
      asa_config:
#        before: "clear configure ntp"
        lines:
          - "ntp server {{ item.ntp_server }}"
        provider: "{{ cli }}"
      tags: ntp_only
      with_items: "{{ ntp_config }}"
